# Site settings
title: The blog
email: mika@sund.land
description: >-
  My blog on technical stuff.
baseurl: ""
url: "https://mika-s.github.io"
twitter_username:
github_username:  mika-s
google_analytics: UA-109270090-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
