# Site settings
title: Mika's tech blog
email: mail@sund.land
description: >-

baseurl: ""
url: "https://mika-s.github.io"
twitter_username:
github_username:  mika-s
google_analytics: G-EMBCKYENNR

header_pages:
  - topics.md
  - about.md

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
