# Site settings
title: Mika's coding blog
email: mail@sund.land
description: >-

baseurl: ""
url: "https://mika-s.github.io"
twitter_username:
github_username:  mika-s
google_analytics: UA-109270090-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
